Repository bloomberg/blazingmq-sdk-java, pull requests merged in 2023-08, with the labels that each got.

#15 Fix: reduce frequent logging
  bmq-sdk/src/main/java/com/bloomberg/bmq/impl/PutPoster.java
  bmq-sdk/src/test/java/com/bloomberg/bmq/it/BrokerSessionStressIT.java
  bmq-sdk/src/test/java/com/bloomberg/bmq/it/SessionStressIT.java
Labels: enhancement

#12 CI: run integration tests with Github Actions
  .github/workflows/build.yaml
  bmq-sdk/pom.xml
  bmq-sdk/src/main/java/com/bloomberg/bmq/impl/PutPoster.java
  bmq-sdk/src/main/java/com/bloomberg/bmq/impl/infr/net/NetResolver.java
  bmq-sdk/src/main/java/com/bloomberg/bmq/impl/infr/util/SystemUtil.java
  bmq-sdk/src/test/bin/docker-build.sh
  bmq-sdk/src/test/docker/Dockerfile
  bmq-sdk/src/test/docker/config/bmqbrkrcfg.json
  bmq-sdk/src/test/docker/config/clusters.json
  bmq-sdk/src/test/docker/config/domains/bmq.test.mmap.fanout.json
  bmq-sdk/src/test/docker/config/domains/bmq.test.mmap.priority.json
  bmq-sdk/src/test/docker/domains.json
  bmq-sdk/src/test/java/com/bloomberg/bmq/impl/infr/net/NetResolverTest.java
  bmq-sdk/src/test/java/com/bloomberg/bmq/it/BrokerSessionIT.java
  bmq-sdk/src/test/java/com/bloomberg/bmq/it/SessionIT.java
  bmq-sdk/src/test/java/com/bloomberg/bmq/it/TcpBrokerConnectionIT.java
  bmq-sdk/src/test/java/com/bloomberg/bmq/it/util/BmqBrokerContainer.java
  bmq-sdk/src/test/java/com/bloomberg/bmq/it/util/TestTools.java
  pom.xml
Labels: A-Build, A-Testing

#18 Set atomic before enqueueing (DIS)CONNECTED event
  .github/workflows/build.yaml
  bmq-sdk/src/main/java/com/bloomberg/bmq/impl/BrokerSession.java
  bmq-sdk/src/test/java/com/bloomberg/bmq/impl/BrokerSessionTest.java
Labels: A-Client
